[workspace]
resolver = "2"

members = [
    "unnamed_engine",
    "unnamed_client",
]

# Build dependencies
[workspace.dependencies.winres]
version = "0.1.12"

# Development dependencies
[workspace.dependencies.serial_test]
version = "3.1.1"

# General dependencies
[workspace.dependencies.thiserror]
version = "1.0.64"

[workspace.dependencies.log]
version = "0.4.22"

[workspace.dependencies.env_logger]
version = "0.11.5"

[workspace.dependencies.strum]
version = "0.26.3"
features = ["derive"]

[workspace.dependencies.crossbeam]
version = "0.8.4"

[workspace.dependencies.winit]
version = "0.30.5"
