[package]
name = "unnamed_engine"
version = "0.1.0"
edition = "2021"

[dev-dependencies.serial_test]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.log]
workspace = true

[dependencies.env_logger]
workspace = true

[dependencies.strum]
workspace = true

[dependencies.crossbeam]
workspace = true

[dependencies.winit]
workspace = true
