[package]
name = "unnamed_client"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies.winres]
workspace = true

[dependencies.unnamed_engine]
path = "../unnamed_engine"

[dependencies.log]
workspace = true

[dependencies.env_logger]
workspace = true

[dependencies.strum]
workspace = true
