name: 🍎 MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Build Debug
      run: cargo build --verbose
    - name: Build Release
      run: cargo build --verbose --release
    - name: Tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Audit
      run: cargo audit
